local LSM = LibStub("LibSharedMedia-3.0")

-- Roboto Fonts
LSM:Register("font", "Roboto 200", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Thin.ttf]])
LSM:Register("font", "Roboto 300", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Light.ttf]])
LSM:Register("font", "Roboto 400", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Regular.ttf]])
LSM:Register("font", "Roboto 500", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Medium.ttf]])
LSM:Register("font", "Roboto 600", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Bold.ttf]])
LSM:Register("font", "Roboto 700", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Black.ttf]])

LSM:Register("font", "Roboto/C 300", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-Light.ttf]])
LSM:Register("font", "Roboto/C 400", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-Regular.ttf]])
LSM:Register("font", "Roboto/C 600", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-Bold.ttf]])

LSM:Register("font", "Roboto/CI 300", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-LightItalic.ttf]])
LSM:Register("font", "Roboto/CI 400", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-Italic.ttf]])
LSM:Register("font", "Roboto/CI 600", [[Interface\AddOns\Oken_Core\media\fonts\RobotoCondensed-BoldItalic.ttf]])

LSM:Register("font", "Roboto/I 200", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-ThinItalic.ttf]])
LSM:Register("font", "Roboto/I 300", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-LightItalic.ttf]])
LSM:Register("font", "Roboto/I 400", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-Italic.ttf]])
LSM:Register("font", "Roboto/I 500", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-MediumItalic.ttf]])
LSM:Register("font", "Roboto/I 600", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-BoldItalic.ttf]])
LSM:Register("font", "Roboto/I 700", [[Interface\AddOns\Oken_Core\media\fonts\Roboto-BlackItalic.ttf]])

LSM:Register("sound", "|cFFFF0000Add|r", [[Interface\Addons\Oken_Core\media\sounds\Add.ogg]])
LSM:Register("sound", "|cFFFF0000Adds|r", [[Interface\Addons\Oken_Core\media\sounds\Adds.ogg]])
LSM:Register("sound", "|cFFFF0000Avoid|r", [[Interface\Addons\Oken_Core\media\sounds\Avoid.ogg]])
LSM:Register("sound", "|cFFFF0000Bait|r", [[Interface\Addons\Oken_Core\media\sounds\Bait.ogg]])
LSM:Register("sound", "|cFFFF0000Beam|r", [[Interface\Addons\Oken_Core\media\sounds\Beam.ogg]])
LSM:Register("sound", "|cFFFF0000Behind|r", [[Interface\Addons\Oken_Core\media\sounds\Behind.ogg]])
LSM:Register("sound", "|cFFFF0000Bloodlust|r", [[Interface\Addons\Oken_Core\media\sounds\Bloodlust.ogg]])
LSM:Register("sound", "|cFFFF0000Bomb|r", [[Interface\Addons\Oken_Core\media\sounds\Bomb.ogg]])
LSM:Register("sound", "|cFFFF0000Break|r", [[Interface\Addons\Oken_Core\media\sounds\Break.ogg]])
LSM:Register("sound", "|cFFFF0000Buff|r", [[Interface\Addons\Oken_Core\media\sounds\Buff.ogg]])
LSM:Register("sound", "|cFFFF0000CC|r", [[Interface\Addons\Oken_Core\media\sounds\CC.ogg]])
LSM:Register("sound", "|cFFFF0000Chain|r", [[Interface\Addons\Oken_Core\media\sounds\Chain.ogg]])
LSM:Register("sound", "|cFFFF0000Clear|r", [[Interface\Addons\Oken_Core\media\sounds\Clear.ogg]])
LSM:Register("sound", "|cFFFF0000Collect|r", [[Interface\Addons\Oken_Core\media\sounds\Collect.ogg]])
LSM:Register("sound", "|cFFFF0000Debuff|r", [[Interface\Addons\Oken_Core\media\sounds\Debuff.ogg]])
LSM:Register("sound", "|cFFFF0000Diamond|r", [[Interface\Addons\Oken_Core\media\sounds\Diamond.ogg]])
LSM:Register("sound", "|cFFFF0000Dispell|r", [[Interface\Addons\Oken_Core\media\sounds\Dispell.ogg]])
LSM:Register("sound", "|cFFFF0000Dodge|r", [[Interface\Addons\Oken_Core\media\sounds\Dodge.ogg]])
LSM:Register("sound", "|cFFFF0000Dont Move|r", [[Interface\Addons\Oken_Core\media\sounds\Dont Move.ogg]])
LSM:Register("sound", "|cFFFF0000Escort|r", [[Interface\Addons\Oken_Core\media\sounds\Escort.ogg]])
LSM:Register("sound", "|cFFFF0000Front|r", [[Interface\Addons\Oken_Core\media\sounds\Front.ogg]])
LSM:Register("sound", "|cFFFF0000Gate|r", [[Interface\Addons\Oken_Core\media\sounds\Gate.ogg]])
LSM:Register("sound", "|cFFFF0000Gather|r", [[Interface\Addons\Oken_Core\media\sounds\Gather.ogg]])
LSM:Register("sound", "|cFFFF0000Green|r", [[Interface\Addons\Oken_Core\media\sounds\Green.ogg]])
LSM:Register("sound", "|cFFFF0000Group1|r", [[Interface\Addons\Oken_Core\media\sounds\Group1.ogg]])
LSM:Register("sound", "|cFFFF0000Group2|r", [[Interface\Addons\Oken_Core\media\sounds\Group2.ogg]])
LSM:Register("sound", "|cFFFF0000Group3|r", [[Interface\Addons\Oken_Core\media\sounds\Group3.ogg]])
LSM:Register("sound", "|cFFFF0000Group4|r", [[Interface\Addons\Oken_Core\media\sounds\Group4.ogg]])
LSM:Register("sound", "|cFFFF0000Group5|r", [[Interface\Addons\Oken_Core\media\sounds\Group5.ogg]])
LSM:Register("sound", "|cFFFF0000Healcd|r", [[Interface\Addons\Oken_Core\media\sounds\Healcd.ogg]])
LSM:Register("sound", "|cFFFF0000Hide|r", [[Interface\Addons\Oken_Core\media\sounds\Hide.ogg]])
LSM:Register("sound", "|cFFFF0000High Energy|r", [[Interface\Addons\Oken_Core\media\sounds\High Energy.ogg]])
LSM:Register("sound", "|cFFFF0000High Stacks|r", [[Interface\Addons\Oken_Core\media\sounds\High Stacks.ogg]])
LSM:Register("sound", "|cFFFF0000Immunity|r", [[Interface\Addons\Oken_Core\media\sounds\Immunity.ogg]])
LSM:Register("sound", "|cFFFF0000Interrupt|r", [[Interface\Addons\Oken_Core\media\sounds\Interrupt.ogg]])
LSM:Register("sound", "|cFFFF0000Invisibility|r", [[Interface\Addons\Oken_Core\media\sounds\Invisibility.ogg]])
LSM:Register("sound", "|cFFFF0000Knock|r", [[Interface\Addons\Oken_Core\media\sounds\Knock.ogg]])
LSM:Register("sound", "|cFFFF0000Left|r", [[Interface\Addons\Oken_Core\media\sounds\Left.ogg]])
LSM:Register("sound", "|cFFFF0000Linked|r", [[Interface\Addons\Oken_Core\media\sounds\Linked.ogg]])
LSM:Register("sound", "|cFFFF0000Melee|r", [[Interface\Addons\Oken_Core\media\sounds\Melee.ogg]])
LSM:Register("sound", "|cFFFF0000Mines|r", [[Interface\Addons\Oken_Core\media\sounds\Mines.ogg]])
LSM:Register("sound", "|cFFFF0000Moon|r", [[Interface\Addons\Oken_Core\media\sounds\Moon.ogg]])
LSM:Register("sound", "|cFFFF0000Move|r", [[Interface\Addons\Oken_Core\media\sounds\Move.ogg]])
LSM:Register("sound", "|cFFFF0000Next|r", [[Interface\Addons\Oken_Core\media\sounds\Next.ogg]])
LSM:Register("sound", "|cFFFF0000Orb|r", [[Interface\Addons\Oken_Core\media\sounds\Orb.ogg]])
LSM:Register("sound", "|cFFFF0000Overlap|r", [[Interface\Addons\Oken_Core\media\sounds\Overlap.ogg]])
LSM:Register("sound", "|cFFFF0000Phase2|r", [[Interface\Addons\Oken_Core\media\sounds\Phase2.ogg]])
LSM:Register("sound", "|cFFFF0000Phase3|r", [[Interface\Addons\Oken_Core\media\sounds\Phase3.ogg]])
LSM:Register("sound", "|cFFFF0000Phase4|r", [[Interface\Addons\Oken_Core\media\sounds\Phase4.ogg]])
LSM:Register("sound", "|cFFFF0000Phase5|r", [[Interface\Addons\Oken_Core\media\sounds\Phase5.ogg]])
LSM:Register("sound", "|cFFFF0000Pots|r", [[Interface\Addons\Oken_Core\media\sounds\Pots.ogg]])
LSM:Register("sound", "|cFFFF0000Purge|r", [[Interface\Addons\Oken_Core\media\sounds\Purge.ogg]])
LSM:Register("sound", "|cFFFF0000Range|r", [[Interface\Addons\Oken_Core\media\sounds\Range.ogg]])
LSM:Register("sound", "|cFFFF0000Right|r", [[Interface\Addons\Oken_Core\media\sounds\Right.ogg]])
LSM:Register("sound", "|cFFFF0000Scatter|r", [[Interface\Addons\Oken_Core\media\sounds\Scatter.ogg]])
LSM:Register("sound", "|cFFFF0000Selfcd|r", [[Interface\Addons\Oken_Core\media\sounds\Selfcd.ogg]])
LSM:Register("sound", "|cFFFF0000Soak|r", [[Interface\Addons\Oken_Core\media\sounds\Soak.ogg]])
LSM:Register("sound", "|cFFFF0000Spellsteal|r", [[Interface\Addons\Oken_Core\media\sounds\Spellsteal.ogg]])
LSM:Register("sound", "|cFFFF0000Spread|r", [[Interface\Addons\Oken_Core\media\sounds\Spread.ogg]])
LSM:Register("sound", "|cFFFF0000Stack|r", [[Interface\Addons\Oken_Core\media\sounds\Stack.ogg]])
LSM:Register("sound", "|cFFFF0000Stopcast|r", [[Interface\Addons\Oken_Core\media\sounds\Stopcast.ogg]])
LSM:Register("sound", "|cFFFF0000Switch|r", [[Interface\Addons\Oken_Core\media\sounds\Switch.ogg]])
LSM:Register("sound", "|cFFFF0000Targeted|r", [[Interface\Addons\Oken_Core\media\sounds\Targeted.ogg]])
LSM:Register("sound", "|cFFFF0000Taunt|r", [[Interface\Addons\Oken_Core\media\sounds\Taunt.ogg]])
LSM:Register("sound", "|cFFFF0000Transition|r", [[Interface\Addons\Oken_Core\media\sounds\Transition.ogg]])
LSM:Register("sound", "|cFFFF0000Turn|r", [[Interface\Addons\Oken_Core\media\sounds\Turn.ogg]])
LSM:Register("sound", "|cFFFF0000Yellow|r", [[Interface\Addons\Oken_Core\media\sounds\Yellow.ogg]])
